---
abstract: 'Simple Syntax JSON RPC 2.0 Server Implementation'
author:
  - 'nqounet <mail@nqou.net>'
build_requires:
  HTTP::Message: '0'
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-RPC-Lite
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  JSON::RPC::Lite:
    file: lib/JSON/RPC/Lite.pm
    version: v1.0.0
requires:
  JSON::RPC::Spec: '0'
  Plack: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/nqounet/p5-json-rpc-lite/issues
  homepage: https://github.com/nqounet/p5-json-rpc-lite
  repository: https://github.com/nqounet/p5-json-rpc-lite.git
version: v1.0.0
x_authority: cpan:NQOUNET
